"""通用记忆领域模型。"""

from memory_mcp.core.domain.capture import (
    AdmissionDecision,
    Candidate,
    CandidateDurability,
    CandidateProposal,
    CaptureOutcome,
    CaptureResult,
    CaptureStatus,
    ExpressionBasis,
    ExtractionMetadata,
    ReviewItem,
    ReviewStatus,
    TurnEnvelope,
    TurnMessage,
)
from memory_mcp.core.domain.lifecycle import (
    MemoryHistoryEntry,
    normalize_memory_text,
)
from memory_mcp.core.domain.maintenance import MaintenanceResult
from memory_mcp.core.domain.models import (
    AssertionKind,
    Evidence,
    EvidenceSourceType,
    LifecycleStatus,
    MemoryItem,
    MemoryRecord,
    MemoryRevision,
    MessageRole,
    PrincipalContext,
    SensitivityLevel,
    VerificationStatus,
)
from memory_mcp.core.domain.recall import (
    RecalledMemory,
    RecallQuery,
    RecallResult,
    RecallSourceSummary,
)
from memory_mcp.core.domain.relations import (
    MemoryRelation,
    MemoryRelationSummary,
    RelationDirection,
    RelationEndpoint,
    RelationOrigin,
    RelationProposal,
    RelationProvenance,
    RelationScope,
    RelationStatus,
)

__all__ = [
    "AdmissionDecision",
    "AssertionKind",
    "Candidate",
    "CandidateDurability",
    "CandidateProposal",
    "CaptureOutcome",
    "CaptureResult",
    "CaptureStatus",
    "Evidence",
    "EvidenceSourceType",
    "ExpressionBasis",
    "ExtractionMetadata",
    "LifecycleStatus",
    "MaintenanceResult",
    "MemoryHistoryEntry",
    "MemoryItem",
    "MemoryRecord",
    "MemoryRelation",
    "MemoryRelationSummary",
    "MemoryRevision",
    "MessageRole",
    "PrincipalContext",
    "RecallQuery",
    "RecallResult",
    "RecallSourceSummary",
    "RecalledMemory",
    "RelationDirection",
    "RelationEndpoint",
    "RelationOrigin",
    "RelationProposal",
    "RelationProvenance",
    "RelationScope",
    "RelationStatus",
    "ReviewItem",
    "ReviewStatus",
    "SensitivityLevel",
    "TurnEnvelope",
    "TurnMessage",
    "VerificationStatus",
    "normalize_memory_text",
]
